### ISSUE TITLE
Archive this feedstock

### ISSUE THREAD

**Issue by xhochy** [conda-forge/scilab-feedstock#22]
Hey @SylvainCorlay (as the sole listed maintainer), are you still interested in this feedstock? It seems unmaintained and pops up as blocking in quite some migrations. Can we archive it until someone has the time to fix it again?

**Comment by SylvainCorlay** [comment]
I pushed things forward quite a bit @xhochy. Is this still blocking things anywhere?

**Comment by xhochy** [comment]
If all is running fine: no. `scilab` just appeared so often as a missing piece in migrations. Seems like all have been solved, thus closing this.
