### ISSUE TITLE
Xconfiguration.xml not found by scilab 

### ISSUE THREAD

**Issue by jcb-mpl** [conda-forge/scilab-feedstock#4]
Issue:
Scilab is installed in a newly installed VM (https://images.galaxyproject.org/planemo/latest.ova), OS=Ubuntu, using the command:  "conda install -c conda-forge scilab". Erevything seems all right. 
But the command "scilab" does not load scilab, problems with "libscijvm"

 "scilab-cli" loads Scilab, with an error message about Xconfiguration.xml file 

![scilab_scilab-cli](https://user-images.githubusercontent.com/52232846/60157499-2d083000-97ef-11e9-9316-661b3cd9419b.png)

Within scilab-cli, "atomsInstall" fails, also with an error message about Xconfiguration.xml file.

![atoms](https://user-images.githubusercontent.com/52232846/60157572-5759ed80-97ef-11e9-8c82-0956c0af34f3.png)

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by SylvainCorlay** [comment]
Thanks for posting @jcb-mpl . I missed this message.

The conda package for scilab only includes `scilab-cli` and not the graphical interface. The issue with the latter is that it requires a *very* outdated version of openjdk which will probably never be packaged for conda-forge.

I posted on the scilab mailing list on this issue and they claimed that the version of openjdk required would be updated for 6.1.

**Comment by SylvainCorlay** [comment]
Closing as answered.
